contact_links:
  - name: Join the Discord for support!
    url: https://discord.gg/c9jqxau5DB
    about: If you would prefer, you can ask for help on Discord. Click here to join the server! From there feel free to DM or @ hii_jax, or just ask for help in one of the text channels!
