name: Report a Malicious User
description: Request a user be added to the ban list. Please fill as many fields as you can.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve player safety in the Webfishing community!
  - type: input
    id: steamid
    attributes:
      label: SteamID
      description: 'A unique identifier that can be added directly to the banlist. Formatted as 7656119##########'
      placeholder: ex. 7656119##########
    validations:
      required: false
  - type: input
    id: steam-profile
    attributes:
      label: Steam Profile Name
      description: 'The current name that appears at the top of their profile page. The user might not be totally identifiable based off of this.'
      placeholder: ex. grincher
    validations:
      required: false
  - type: input
    id: steam-profile
    attributes:
      label: Link to Steam Profile
      description: 'Can be found by right clicking on the users profile and clicking "Copy Page URL"'
      placeholder: ex. https://steamcommunity.com/profiles/76561199220832861
    validations:
      required: false
  - type: textarea
    id: reasoning
    attributes:
      label: Reasoning
      description: What troublesome activities were this user committing?
      placeholder: ex. They were threatening users personal information
    validations:
      required: true
  - type: textarea
    id: extra-details
    attributes:
      label: Extra Details
      description: Provide any extra information you think might be helpful. You can add screenshots too if you'd like.
    validations:
      required: false
